---

- name: Define our max swap file size if not passed into the system
  set_fact:
    max_swapfile_size: 2147483648 # 2 Gigs in Kilobytes WRONG!!!! it's 2048 GB
    #max_swapfile_size: 2097152 # 2 Gigs in Kilobytes
  when: max_swapfile_size|default(false) == false

- name: Define our swapfile path if not passed into the system
  set_fact:
    swapfile: '/swap'
  when: swapfile|default(false) == false

- name: Get available system memory
  shell: "grep MemTotal /proc/meminfo | awk {'print $2'}"
  changed_when: false
  register: memory_facts

- name: Display results
  debug:
    msg: "Memory is {{ memory_facts.stdout }} KB, or {{ (memory_facts.stdout|int / (1024|pow(2))) | round(2, 'ceil') }} GB"

- block:
    - debug: msg="Memory is less than or equal to {{ max_swapfile_size }}MB or {{ (max_swapfile_size|int / (1024|pow(2))) | round(2, 'ceil') }} GB"
    - name: Create the file to be used for swap when memory is less than or equal to max swapfile size
      #command: dd if=/dev/zero of="{{ swapfile }}" bs=1024 count="{{ memory_facts.stdout }}"
      command: fallocate -l "{{ (memory_facts.stdout|int / (1024|pow(2))) | round(0, 'ceil') | int  }}" "{{ swapfile }}"
  when: memory_facts.stdout|int <= max_swapfile_size

- block:
    - debug: msg="Memory is greater than {{ max_swapfile_size }}MB or {{ (max_swapfile_size|int / (1024|pow(2))) | round(2, 'ceil') }} GB"
    - name: Create the file to be used for swap when memory is greater than max swapfile size
      command: dd if=/dev/zero of="{{ swapfile }}" bs=1024 count="{{ max_swapfile_size }}"
  when: memory_facts.stdout|int > max_swapfile_size

- name: Format the file for swap
  command: mkswap "{{ swapfile }}"

- name: Change swap file permissions
  file:
    path: "{{ swapfile }}"
    owner: root
    group: root
    mode: 0600

- name: Add the file to the system as a swap file
  command: swapon "{{ swapfile }}"

- name: write swap entry in fstab
  mount:
    name: none
    src: "{{ swapfile }}"
    fstype: swap
    opts: 'sw'
    passno: 0
    dump: 0
    state: present
