---

- name: Install docker pre-requisites
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

#- name: Remove existing docker install
#  package:
#    name: "{{ item }}"
#    state: absent
#  with_items:
#    - docker
#    - docker-client
#    - docker-client-latest
#    - docker-common
#    - docker-latest
#    - docker-latest-logrotate
#    - docker-logrotate
#    - docker-selinux
#    - docker-engine-selinux
#    - docker-engine
#  ignore_errors: true
#
#- name: Install "docker"
#  package:
#    name: "docker"
#    state: present

- name: Ensure the group ec2-service exists
  group:
    name: ec2-service
    gid: 1000
    state: present

- name: Ensure our ec2-service user exists
  user:
    name: ec2-service
    uid: 1000
    groups: ec2-service
    state: present

- name: Ensure our ec2-user is in the ec2-service group
  user:
    name: ec2-user
    groups: ec2-service
    append: yes
    state: present


- name: Get our user with UID of 1000
  getent:
    database: passwd
    key: 1000
  register: uid_data

- name: Allow our user to run docker without sudo
  user:
    name: "{{ uid_data.ansible_facts.getent_passwd.keys().0 }}"
    groups: docker
    append: true
  become: true


- name: Install docker-compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: +x
  become: true

- name: Start docker service
  service:
    name: docker
    state: started
