---

- name: Ensure NFS is installed.
  yum:
    name: nfs-utils
    state: present
    become: true

- name: Ensure mount directory exists.
  file:
    path: "{{ efs_mount_dir }}"
    state: directory
    mode: 0777

- name: Get current AZ from AWS.
  uri:
    url: http://169.254.169.254/latest/meta-data/placement/availability-zone
    return_content: yes
  register: aws_current_az

- name: Ensure EFS volume is mounted.
  mount:
    name: "{{ efs_mount_dir }}"
    src: "{{ aws_current_az.content }}.{{ efs_file_system_id }}.efs.{{ region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1
    state: mounted
