---

- name: Create mount directory
  become: yes
  file:
    path: "{{ efs_mount_dir }}"
    state: directory
    owner: "{{ efs_mount_user|default('hmpps_sys_user') }}"
    group: "{{ efs_mount_user|default('hmpps_sys_user') }}"

- name: Update mount directory permissions
  become: yes
  file:
    path: "{{ efs_mount_dir }}"
    owner: "{{ efs_mount_user|default('hmpps_sys_user') }}"
    group: "{{ efs_mount_user|default('hmpps_sys_user') }}"
    mode: 0755
    recurse: yes

- name: Mount Dir on EFS Volume
  become: yes
  mount:
    path: "{{ efs_mount_dir }}"
    src: "{{ jira_data_volume_id }}"
    fstype: efs
    opts: tls
    state: mounted
