---

- name: Set ec2 facts
  include: facts.yml

- name: Enable epel repository
  include: epel-repository.yml

- name: Install some base packages
  include: packages.yml

- name: Configure our timezone
  include: timezone.yml

- name: Configure system hostname
  include: hostname.yml

- name: Set up cloudwatch logging
  include: cloudwatch.yml
  when: cldwatch_log_group|default(False)

- name: Configure bash prompt
  include: bash-prompt.yml

- name: Create our swapfile
  include: create-swap-file.yml
  when: ansible_env.CONFIGURE_SWAP|default(False)

- name: Enable passwordless sudo for predifined groups
  include: enable-sudoers.yml
  when: enable_sudoers|default(true)

- block:
    - name: Find and mount our ebs volume if specified
      include: volumes.yml
  when: mount_point|default(false)

- block:
    - name: Find and mount our ebs volumes if specified
      include: multiple-volumes.yml
      with_items: "{{ mount_points }}"
      loop_control:
        loop_var: mount
  when: mount_points|default(False)

- block:
    - name: Configure out lvm disks if enabled
      include: lvm.yml
  when: lvm_mount_point|default(false)

- name: Install docker and compose if needed
  include: docker.yml
  when: ansible_env.HAS_DOCKER|default(False)

- name: Self register ourselves on route53
  include: route53-registration.yml
  when: ansible_env.SELF_REGISTER|default(False)

- name: Enable some maintenance crons
  include: crons.yml
