---

- name: Set ec2 facts
  include: facts.yml

- name: Enable epel repository
  include: epel-repository.yml

- name: Install some base packages
  include: packages.yml

- name: Configure our timezone
  include: timezone.yml

- name: Configure system hostname
  include: hostname.yml

- name: Set up cloudwatch logging
  include: cloudwatch.yml
  when: cldwatch_log_group|default(False)

- name: Configure bash prompt
  include: bash-prompt.yml

- name: Find and mount our ebs volume if specified
  include: volumes.yml
  when: mount_point|default(False)

- name: Install docker and compose if needed
  include: docker.yml
  when: ansible_env.HAS_DOCKER|default(False)

- name: Self register ourselves on route53
  include: route53-registration.yml
  when: ansible_env.SELF_REGISTER|default(False)

