---

- name: Set ec2 facts
  include: facts.yml

- name: Configure our timezone
  include: timezone.yml

- name: Configure system hostname
  include: hostname.yml

- name: Configure bash prompt
  include: bash-prompt.yml

- name: Find and mount our ebs volumes
  include: volumes.yml
  when: mount_point|default(False)